version: '3'
services:
    #PHP Service
    app:
        container_name: pvapp_app
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel/php
        # restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        environment: # IMP!: these variables overrides .env of application!!
            SERVICE_NAME: app
            SERVICE_TAGS: dev
            APP_ENV: ${APP_ENV} # local from .env
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx  # :1.10.3
        container_name: pvapp_webserver
        # restart: unless-stopped
        tty: true
        ports:
            - "8082:80"
        #  - "44385:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql  # :5.7.29
        container_name: pvapp_db
        # restart: unless-stopped
        tty: true
        ports:
            - "3309:3306"
        environment:
            # docker create db and 'root' user with below info
            # non-root user can be created directly into db (for ex. via web with adminer)
            MYSQL_DATABASE: pvapp # ${DB_DATABASE}  #  get it from .env file!
            MYSQL_ROOT_PASSWORD: secret # ${DB_ROOT_PASSWORD}
            MYSQL_USER: pvapp # ${DB_USERNAME}
            MYSQL_PASSWORD: pvapp # ${DB_PASSWORD}
            SERVICE_NAME: mysql
            SERVICE_TAGS: dev
        volumes:
            - dbdata:/var/lib/mysql-files/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

    # Supervisor queue worker monitor
#    supervisor:
#        container_name: pvapp_supervisor
#        build:
#            context: .
#            dockerfile: docker/supervisor/supervisor_dockerfile
#        tty: true
#        volumes:
#            - ./:/var/www
#            - ./docker/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
#            # - ./storage/logs/laravel-worker.log:/var/log/supervisor/laravel-worker.log
#        depends_on:
#            - app
#            - webserver
#            - db
#        networks:
#            - app-network

        #Cron
        #cron:
        # build:
        #   context: ./docker/scheduler
        #   dockerfile: Scheduler_dockerfile
        # tty: true
        # volumes:
        #   - ./:/var/www
        #   - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        # entrypoint: sh /var/www/docker/scheduler/crontab.sh
        # depends_on:
        #   - app
        # #we don't need ports with this because it will execute the crontab
        # # ports:
        # #   - 3000:3000
        # networks:
        #   - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge

#Volumes
volumes:
    dbdata:
        driver: local

