# FROM node:16.13.0
FROM node:16.20.2
# RUN npm install -g npm@8.1.4
RUN npm install -g npm@8.19.4
RUN npm install -g @vue/cli
WORKDIR /var/www/frontend/app
COPY frontend/app/package*.json ./
RUN npm install
COPY frontend/app/ .
RUN npm run build
USER node
EXPOSE 3000
# CMD ["npm", "run", "serve"]

